# Generated by Django 4.1.1 on 2022-10-20 01:51

from django.db import migrations, models
import django.db.models.deletion
import project.storages_backends


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=project.storages_backends.PrivateMediaStorage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="blowing_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Direction"),
                    ("N", "North"),
                    ("S", "South"),
                    ("E", "East"),
                    ("W", "West"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hazards",
                to="customers.customer",
            ),
        ),
    ]
