# Generated by Django 4.1.1 on 2022-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="order",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hazard",
            name="content",
            field=models.CharField(blank=True, default="", max_length=250),
            preserve_default=False,
        ),
    ]
