# Generated by Django 4.1.1 on 2023-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_route_routetype_session_route_type_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
    ]
