# Generated by Django 4.1.1 on 2023-10-05 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_session_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="current_customer",
        ),
        migrations.AddField(
            model_name="session",
            name="current_membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="customers.membership",
            ),
        ),
    ]
