# Generated by Django 4.1.1 on 2024-01-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_remove_session_current_customer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership", options={"ordering": ["order"]},
        ),
    ]
